# Generated by Django 4.2.14 on 2024-11-04 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_agent', to='analytics.agent')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_agent', to='analytics.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edges', models.ManyToManyField(to='analytics.edge')),
                ('nodes', models.ManyToManyField(to='analytics.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('query_id', models.AutoField(primary_key=True, serialize=False)),
                ('query', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.IntegerField()),
                ('token_usage', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.graph')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.query')),
            ],
        ),
    ]
