# Generated by Django 4.2.14 on 2024-11-05 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_agent_id_alter_edge_id_alter_graph_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_usage', models.IntegerField()),
                ('startTimestamp', models.DateTimeField()),
                ('endTimestamp', models.DateTimeField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.agent')),
            ],
        ),
        migrations.RenameField(
            model_name='query',
            old_name='query_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='query',
            old_name='query',
            new_name='query_text',
        ),
        migrations.RemoveField(
            model_name='query',
            name='user',
        ),
        migrations.AddField(
            model_name='query',
            name='graph',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.graph'),
        ),
        migrations.DeleteModel(
            name='Workflow',
        ),
        migrations.AddField(
            model_name='agentquery',
            name='queryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.query'),
        ),
    ]
