# Generated by Django 4.2.14 on 2024-11-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_agentquery_rename_query_id_query_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='hash',
            field=models.CharField(default='NONE', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
