# Generated by Django 4.2.14 on 2024-11-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_graph_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='model_name',
            field=models.CharField(default='GPT-4o', max_length=20),
        ),
    ]
