# Generated by Django 4.2.14 on 2024-11-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_agent_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentquery',
            name='response',
            field=models.TextField(default='DEFAULT_RESPONSE'),
        ),
    ]
